spring.application.name: authserver
spring.config.import: optional:configserver:http://${app.config-server}:8888
server.port: 9999

app.config-server: localhost

spring:
  datasource:
    url: jdbc:mysql://${app.database.url}:3306/api-service?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      client_id: ${app.security.jwt.client_id}
      client_secret: ${app.security.jwt.client_secret}
      grant_type: password
      refresh_token: refresh_token
      access_token_validity_seconds: 3600
      fresh_token_validity_seconds: 31536000