server:
  port: 9999

spring:
  security:
    jwt:
      client_id: api-client
      client_secret: api-secret
      grant_type: password
      refresh_token: refresh_token
      access_token_validity_seconds: 3600
      fresh_token_validity_seconds: 21600
  h2:
    console:
      enabled: true
      path: /h2-console
